clc;
clear;
close all;
A=1;
omega=2*pi*1;
phi=pi/4;
t=0:0.01:2;
z=A*exp(1j*(omega*t+phi));
real_part=real(z);
imag_part=imag(z);
figure;
plot(t,real_part,'b','LineWidth',2);
hold on;
plot(t,imag_part,'r','LineWidth',2);
title('Complex Signal: Real and Imaginary Parts');
xlabel('Time(s)');
ylabel('Amplitude');
legend('Real Part','Imaginary Part');
grid on;